version: '2'
services:
  db:
    image: redis:alpine
  web-api:
    image: pugstunt/mastermind-api:latest
    links:
      - db
    environment:
      - environment=production
      - redis.connection.string=redis://db:6379
  web-ui:
    image: pugstunt/mastermind-ui:latest
    ports:
      - "80:80"
    links:
      - "web-api:api"
